name: "Execute Migration Command"
description: "Execute Migration Commands..."
inputs:
  tempenv-version:
    description: 'The dotnet version to use'
    default: "testenv-e2e-2"
    required: true
  access-key:
    description: 'AWS Access Key from secrets'
    required: true
  secret-key:
    description: 'AWS Secret Key from secrets'
    required: true
  default-region:
    description: 'AWS Default Region from secrets'
    required: true
  # account-id:
  #   description: 'AWS Account ID for ECR  from secrets'
  #   required: true
  oleksb-key:
    description: 'Public key for adding to server from secrets'
    required: true
  host_ip:
    description: 'IP addres of remote host'
    required: true

runs:
  using: "composite"
  steps: 

    - name: Recreate DB
      uses: appleboy/ssh-action@master
      if: ${{ inputs.tempenv-version == 'testenv-e2e-2' || startsWith(inputs.tempenv-version, 'e2e-') }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret-key }}
        AWS_DEFAULT_REGION: ${{ inputs.default-region }}
        # RESOURCES_AWS_ACCOUNT_ID: ${{ inputs.account-id }}
        ENV_NAME: ${{ inputs.tempenv-version }}
      with:
        host: ${{ inputs.host_ip }}
        username: ubuntu
        key: ${{ inputs.oleksb-key }}
        port: 22
        script: |
          sudo docker exec tabula_backend php delete_db.php
          sudo docker exec tabula_backend php create_db.php
        shell: bash

    - name: Run default migration
      uses: appleboy/ssh-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret-key }}
        AWS_DEFAULT_REGION: ${{ inputs.default-region }}
        # RESOURCES_AWS_ACCOUNT_ID: ${{ inputs.account-id }}
        ENV_NAME: ${{ inputs.tempenv-version }}
      with:
        host: ${{ inputs.host_ip }}
        username: ubuntu
        key: ${{ inputs.oleksb-key }}
        port: 22
        script: |
          sudo docker exec tabula_backend php index.php migrate
        shell: bash

    - name: Run migrations
      uses: appleboy/ssh-action@master
      if: ${{ inputs.tempenv-version == 'testenv-e2e-2' || startsWith(inputs.tempenv-version, 'e2e-') || startsWith(inputs.tempenv-version, 'sandbox') }}
#      if: ${{ inputs.tempenv-version == 'testenv-e2e-2' || startsWith(inputs.tempenv-version, 'e2e-') || startsWith(inputs.tempenv-version, 'prep-02') }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret-key }}
        AWS_DEFAULT_REGION: ${{ inputs.default-region }}
        # RESOURCES_AWS_ACCOUNT_ID: ${{ inputs.account-id }}
        ENV_NAME: ${{ inputs.tempenv-version }}
      with:
        host: ${{ inputs.host_ip }}
        username: ubuntu
        key: ${{ inputs.oleksb-key }}
        port: 22
        script: |
          sudo docker exec tabula_backend php index.php migrate version 1
          sudo docker exec tabula_backend php index.php migrate devdata
          sudo docker exec tabula_backend php index.php migrate testdata
          sudo docker exec tabula_backend php index.php migrate
        shell: bash

    - name: Run migrations for e2e tests on prep-02
      uses: appleboy/ssh-action@master
      if: ${{ startsWith(inputs.tempenv-version, 'prep-02') || startsWith(inputs.tempenv-version, 'sandbox') }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret-key }}
        AWS_DEFAULT_REGION: ${{ inputs.default-region }}
        # RESOURCES_AWS_ACCOUNT_ID: ${{ inputs.account-id }}
        ENV_NAME: ${{ inputs.tempenv-version }}
      with:
        host: ${{ inputs.host_ip }}
        username: ubuntu
        key: ${{ inputs.oleksb-key }}
        port: 22
        script: |
          sudo docker exec tabula_backend php index.php migrate testdata
        shell: bash
