name: "Execute Deploy Command"
description: "Execute Deploy Command..."
inputs:
  tempenv-version:
    description: 'The dotnet version to use'
    default: "testenv-e2e-2"
    required: true
  access-key:
    description: 'AWS Access Key from secrets'
    required: true
  secret-key:
    description: 'AWS Secret Key from secrets'
    required: true
  default-region:
    description: 'AWS Default Region from secrets'
    required: true
  account-id:
    description: 'AWS Account ID for ECR  from secrets'
    required: true
  oleksb-key:
    description: 'Public key for adding to server from secrets'
    required: true
  host_ip:
    description: 'IP addres of remote host'
    required: true
  resource-access-key:
    description: 'Resource AWS Access Key from secrets'
    required: true
    default: ""
  resource-secret-key:
    description: 'Resource AWS Secret Key from secrets'
    required: true
    default: ""
    
runs:
  using: "composite"
  steps: 

    - name: Create AWS credentials file
      uses: appleboy/ssh-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret-key }}
        AWS_DEFAULT_REGION: ${{ inputs.default-region }}
        RESOURCES_ACCESS_KEY_ID: ${{ inputs.resource-access-key }}
        RESOURCES_SECRET_ACCESS_KEY: ${{ inputs.resource-secret-key }}
      with:
        host: ${{ inputs.host_ip }}
        username: ubuntu
        key: ${{ inputs.oleksb-key }}
        port: 22
        script: |
          rm -rf ~/.aws
          mkdir ~/.aws
          touch ~/.aws/credentials
          chmod 600 ~/.aws/credentials
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[resources]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ env.RESOURCES_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ env.RESOURCES_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

    - name: copy docker-compose via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.host_ip }}
        username: ubuntu
        port: 22
        key: ${{ inputs.oleksb-key }}
        source: "./application/config/delete_db.php,./application/config/create_db.php,./deploy/docker-compose.yaml.template,./application/config/env,./.htaccess.example"
        target: "/home/ubuntu"

    - name: Start docker-compose
      uses: appleboy/ssh-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret-key }}
        AWS_DEFAULT_REGION: ${{ inputs.default-region }}
        RESOURCES_AWS_ACCOUNT_ID: ${{ inputs.account-id }}
        ENV_NAME: ${{ inputs.tempenv-version }}
      with:
        host: ${{ inputs.host_ip }}
        username: ubuntu
        key: ${{ inputs.oleksb-key }}
        port: 22
        script: |
          whoami
          ls -al
          cp ./application/config/env ./.env
          cp ./.htaccess.example ./.htaccess
          aws ecr get-login-password --profile resources --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ env.RESOURCES_AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          sudo docker rm -f $(sudo docker ps -a | awk '{print $1}') | true
          sudo docker rmi --force $(sudo docker images --all -q) | true
          export ENV_NAME=${{ env.ENV_NAME }}
          export RESOURCES_AWS_ACCOUNT_ID=${{ env.RESOURCES_AWS_ACCOUNT_ID }}
          docker-compose -f ./deploy/docker-compose.yaml.template config > ./deploy/docker-compose.yaml
          sudo docker-compose -f ./deploy/docker-compose.yaml up -d
        shell: bash
