name: "Run e2e test"
description: "Run tests..."
inputs:
  dotnet-version:
    description: 'The dotnet version to use'
    default: '6.0.x'
    required: false
  backend-url:
    description: 'URL to tabula deployed'
    required: true
  tabula-login:
    description: 'Login to tabula portal'
    required: true
  tabula-password:
    description: 'Password to tabula portal'
    required: true



runs:
  using: "composite"
  steps: 
    # - name: Checkout tabula-automation-tests infra repo
    #   uses: actions/checkout@master
    #   with:
    #     repository: eScribers/tabula-automation-tests
    #     ref: refs/heads/master
    #     token: ${{ secrets.GIT_TOKEN }}
    #     path: 'e2e'

    - name: Define variables 
      run: |
           echo "BACKEND_URL=${{ inputs.backend-url }}" >> $GITHUB_ENV
           echo "TABULA_LOGIN=${{ inputs.tabula-login }}" >> $GITHUB_ENV
           echo "TABULA_PASSWORD=${{ inputs.tabula-password }}" >> $GITHUB_ENV
      shell: bash

    - name: Setup env file
      uses: cuchi/jinja2-action@v1.2.0
      with:
        template: ./e2e/common/TestSuites/Authentication/Authentication.xml.j2
        output_file: ./e2e/common/TestSuites/Authentication/Authentication.xml
        strict: true
        variables: |
          BACKEND_URL=${{ env.BACKEND_URL }}
          TABULA_LOGIN=${{ env.TABULA_LOGIN }}
          TABULA_PASSWORD=${{ env.TABULA_PASSWORD }}

    - name: Show Authentication.xml
      run: |
        cat ./e2e/common/TestSuites/Authentication/Authentication.xml
      shell: bash

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install GoogleChrome Driver
      run: |
        google-chrome --version 
        chromedriver --version
        wget https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
        google-chrome --version 
        chromedriver --version
      shell: bash

    - name: Build project
      run: |
        dotnet build ./e2e 
      shell: bash

    - name: Run tests
      run: |
        google-chrome --version 
        chromedriver --version
        ./e2e/TestPerformer/bin/Debug/net6.0/TestPerformer load ./e2e/Automation.Tests/bin/Debug/netcoreapp3.1/Automation.Tests.dll // run ./e2e/common/TestSuites/Authentication/Authentication.xml
        ls -l ./e2e/TestPerformer/bin/Debug/net6.0/Reports/*
      shell: bash
