name: "Run e2e test"
description: "Run tests..."
inputs:
  dotnet-version:
    description: 'The dotnet version to use'
    default: '6.0.x'
    required: false
  backend-url:
    description: 'URL to tabula deployed'
    required: true
  tabula-login:
    description: 'Login to tabula portal'
    required: true
  tabula-password:
    description: 'Password to tabula portal'
    required: true
  access-key:
    description: 'AWS Access Key from secrets'
    required: true
  secret-key:
    description: 'AWS Secret Key from secrets'
    required: true
  token:
    description: 'Token to github'
    required: true

runs:
  using: "composite"
  steps: 
    - name: Checkout devops infra repo
      uses: actions/checkout@master
      with:
        repository: eScribers/tabula-automation-tests
        ref: refs/heads/master
        token: ${{ inputs.token }}

    - name: Define variables 
      run: |
           echo "BACKEND_URL=${{ inputs.backend-url }}" >> $GITHUB_ENV
           echo "TABULA_LOGIN=${{ inputs.tabula-login }}" >> $GITHUB_ENV
           echo "TABULA_PASSWORD=${{ inputs.tabula-password }}" >> $GITHUB_ENV
      shell: bash

    - name: Setup env file
      uses: cuchi/jinja2-action@v1.2.0
      with:
        template: ./common/TestSuites/Authentication/Authentication.xml.j2
        output_file: ./common/TestSuites/Authentication/Authentication.xml
        strict: true
        variables: |
          BACKEND_URL=${{ env.BACKEND_URL }}
          TABULA_LOGIN=${{ env.TABULA_LOGIN }}
          TABULA_PASSWORD=${{ env.TABULA_PASSWORD }}
          SENDER_EMAIL_ADDRESS=""
          SENDER_EMAIL_PASSWORD=""
          PR_NUMBER=""
          PROJECT_REPO=""
          ACTION_ID=""

    - name: Show Authentication.xml
      run: |
        cat ./common/TestSuites/Authentication/Authentication.xml
      shell: bash

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install GoogleChrome Driver
      run: |
        google-chrome --version 
        chromedriver --version
        wget https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
        google-chrome --version 
        chromedriver --version
      shell: bash

    - name: Build project
      run: |
        dotnet build 
      shell: bash

    - name: Run tests
      run: |
        google-chrome --version 
        chromedriver --version
        ./TestPerformer/bin/Debug/net6.0/TestPerformer load ./Automation.Tests/bin/Debug/netcoreapp3.1/Automation.Tests.dll // run ./common/TestSuites/Authentication/Authentication.xml
      shell: bash


    - name: Add credentials to Amazon 
      uses: "aws-actions/configure-aws-credentials@v1"
      if: always()
      with:
        aws-access-key-id: "${{ inputs.access-key }}"
        aws-region: "us-east-1"
        aws-secret-access-key: "${{ inputs.secret-key }}"

    - name: Upload report to S3
      if: always()
      run: |
        aws s3 cp ./TestPerformer/bin/Debug/net6.0/Reports/ s3://escribers-automation-tests-e2e-reports/ --recursive 
      shell: bash

