name: "Run e2e test"
description: "Run tests..."
inputs:
  pr-number:
    description: 'PR number where those tests was executed'
    default: ""
  project-repo:
    description: 'Project repo was tested'
    default: ""
  action-id:
    description: 'Action ID for preparint link to workflow'
    default: ""
  sender-email-address:
    description: 'Git reference from where it should be deployed'
    default: ""
  sender-email-password:
    description: 'Git reference from where it should be deployed'
    default: ""
  git-reference:
    description: 'Git reference from where it should be deployed'
    default: "refs/heads/master"
  dotnet-version:
    description: 'The dotnet version to use'
    default: '6.0.x'
    required: false
  backend-url:
    description: 'URL to tabula deployed'
    required: true
  tabula-login:
    description: 'Login to tabula portal'
    required: true
  tabula-password:
    description: 'Password to tabula portal'
    required: true
  access-key:
    description: 'AWS Access Key from secrets'
    required: true
  secret-key:
    description: 'AWS Secret Key from secrets'
    required: true
  token:
    description: 'Token to github'
    required: true
  pr-title:
    description: 'PR Title'
    required: false
  pr-creator:
    description: 'PR Author'
    required: false

runs:
  using: "composite"
  steps: 
    - name: Checkout tabula-automation-tests repo
      uses: actions/checkout@v2
      with:
        repository: eScribers/tabula-automation-tests
        ref: ${{ inputs.git-reference }}
        token: ${{ inputs.token }}

    - name: Define variables 
      run: |
           echo "BACKEND_URL=${{ inputs.backend-url }}" >> $GITHUB_ENV
           echo "TABULA_LOGIN=${{ inputs.tabula-login }}" >> $GITHUB_ENV
           echo "TABULA_PASSWORD=${{ inputs.tabula-password }}" >> $GITHUB_ENV
      shell: bash

    - name: Setup Smoke.xml file
      uses: cuchi/jinja2-action@v1.2.0
      with:
        template: ./common/TestSuites/SmokeE2E/Smoke.xml.j2
        output_file: ./common/TestSuites/SmokeE2E/Smoke.xml
        strict: true
        variables: |
          BACKEND_URL=${{ env.BACKEND_URL }}
          TABULA_LOGIN=${{ env.TABULA_LOGIN }}
          TABULA_PASSWORD=${{ env.TABULA_PASSWORD }}
          SENDER_EMAIL_ADDRESS=${{ inputs.sender-email-address }}
          SENDER_EMAIL_PASSWORD=${{ inputs.sender-email-password }}
          PR_NUMBER=${{ inputs.pr-number }}
          PROJECT_REPO=${{ inputs.project-repo }}
          ACTION_ID=${{ inputs.action-id }}
          PR_TITLE=${{ inputs.pr-title }}
          PR_AUTHOR=${{ inputs.pr-creator }}

    - name: Setup Smoke.xml file
      uses: cuchi/jinja2-action@v1.2.0
      with:
        template: ./common/TestSuites/SmokeE2E/Login.xml.j2
        output_file: ./common/TestSuites/SmokeE2E/Login.xml
        strict: true
        variables: |
          BACKEND_URL=${{ env.BACKEND_URL }}
          TABULA_LOGIN=${{ env.TABULA_LOGIN }}
          TABULA_PASSWORD=${{ env.TABULA_PASSWORD }}
          SENDER_EMAIL_ADDRESS=${{ inputs.sender-email-address }}
          SENDER_EMAIL_PASSWORD=${{ inputs.sender-email-password }}
          PR_NUMBER=${{ inputs.pr-number }}
          PROJECT_REPO=${{ inputs.project-repo }}
          ACTION_ID=${{ inputs.action-id }}
          PR_TITLE=${{ inputs.pr-title }}
          PR_AUTHOR=${{ inputs.pr-creator }}

    - name: Show Authentication.xml
      run: |
        cat ./common/TestSuites/SmokeE2E/Smoke.xml
        echo ============
        cat ./Automation.Tests/Authentication/Login.cs
      shell: bash

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install GoogleChrome Driver
      run: |
        google-chrome --version 
        chromedriver --version
        wget --no-verbose https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
        wget --no-verbose https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_101.0.4951.64-1_amd64.deb
        ls -l 
        sudo dpkg -i google-chrome-stable_101.0.4951.64-1_amd64.deb
        sudo apt-get install -fy
        google-chrome --version 
        chromedriver --version
      shell: bash

    - name: Build project
      run: |
        dotnet build 
      shell: bash

    - name: Execute prelogin
      run: |
        google-chrome --version
        chromedriver --version
        ./TestPerformer/bin/Debug/net6.0/TestPerformer load ./Automation.Tests/bin/Debug/netcoreapp3.1/Automation.Tests.dll // run ./common/TestSuites/SmokeE2E/Login.xml
      shell: bash

    - name: Run tests
      run: |
        google-chrome --version 
        chromedriver --version
        ./TestPerformer/bin/Debug/net6.0/TestPerformer load ./Automation.Tests/bin/Debug/netcoreapp3.1/Automation.Tests.dll // run ./common/TestSuites/SmokeE2E/Smoke.xml
      shell: bash


    - name: Add credentials to Amazon 
      uses: "aws-actions/configure-aws-credentials@v1"
      if: always()
      with:
        aws-access-key-id: "${{ inputs.access-key }}"
        aws-region: "us-east-1"
        aws-secret-access-key: "${{ inputs.secret-key }}"

    - name: Upload report to S3
      if: always()
      run: |
        aws s3 cp ./TestPerformer/bin/Debug/net6.0/Reports/ s3://escribers-automation-tests-e2e-reports/ --recursive 
      shell: bash

